title: Anwibud
description: Strona firmy budowlanej
#theme: minima
baseurl: "/Anwibud-jekyll" # nie zmieniaj, bo używasz niestandardowej domeny
url: "https://prawienocski.github.io" # lub docelowa domena
permalink: pretty
markdown: kramdown
